# Generated by Django 2.0.4 on 2018-10-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolfood',
            name='when',
        ),
        migrations.AddField(
            model_name='poolfood',
            name='where',
            field=models.CharField(default='', max_length=200, verbose_name='From Where'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poolfood',
            name='waittime',
            field=models.BigIntegerField(verbose_name='Wait time'),
        ),
    ]
